//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось запустить компановку.
        /// </summary>
        public static string CanNotStartPlacing {
            get {
                return ResourceManager.GetString("CanNotStartPlacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось запустить трассировку.
        /// </summary>
        public static string CanNotStartTracing {
            get {
                return ResourceManager.GetString("CanNotStartTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДонНТУ.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть консоль.
        /// </summary>
        public static string ConsoleButtonName_Hide {
            get {
                return ResourceManager.GetString("ConsoleButtonName_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать консоль.
        /// </summary>
        public static string ConsoleButtonName_Show {
            get {
                return ResourceManager.GetString("ConsoleButtonName_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моделирование.
        /// </summary>
        public static string ControlPanel_Modeling {
            get {
                return ResourceManager.GetString("ControlPanel_Modeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компановать.
        /// </summary>
        public static string ControlPanel_Modeling_Place {
            get {
                return ResourceManager.GetString("ControlPanel_Modeling_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трассировать.
        /// </summary>
        public static string ControlPanel_Modeling_Trace {
            get {
                return ResourceManager.GetString("ControlPanel_Modeling_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение.
        /// </summary>
        public static string ControlPanel_Performance {
            get {
                return ResourceManager.GetString("ControlPanel_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматическое.
        /// </summary>
        public static string ControlPanel_Performance_Auto {
            get {
                return ResourceManager.GetString("ControlPanel_Performance_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошаговое.
        /// </summary>
        public static string ControlPanel_Performance_StepByStep {
            get {
                return ResourceManager.GetString("ControlPanel_Performance_StepByStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод компановки.
        /// </summary>
        public static string ControlPanel_PlaceMethod {
            get {
                return ResourceManager.GetString("ControlPanel_PlaceMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод трассировки.
        /// </summary>
        public static string ControlPanel_TraceMethod {
            get {
                return ResourceManager.GetString("ControlPanel_TraceMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим работы.
        /// </summary>
        public static string ControlPanel_WorkMode {
            get {
                return ResourceManager.GetString("ControlPanel_WorkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демонстрационный.
        /// </summary>
        public static string ControlPanel_WorkMode_Demo {
            get {
                return ResourceManager.GetString("ControlPanel_WorkMode_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычный.
        /// </summary>
        public static string ControlPanel_WorkMode_Normal {
            get {
                return ResourceManager.GetString("ControlPanel_WorkMode_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель управления.
        /// </summary>
        public static string ControlPanelName {
            get {
                return ResourceManager.GetString("ControlPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string DialogBox_InfoTitle {
            get {
                return ResourceManager.GetString("DialogBox_InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string DialogBox_WarningTitle {
            get {
                return ResourceManager.GetString("DialogBox_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть панель управления.
        /// </summary>
        public static string ExpandControlPanel {
            get {
                return ResourceManager.GetString("ExpandControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string FullControlPanel_AboutButtonName {
            get {
                return ResourceManager.GetString("FullControlPanel_AboutButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string FullControlPanel_InfoGroupName {
            get {
                return ResourceManager.GetString("FullControlPanel_InfoGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходные данные.
        /// </summary>
        public static string FullControlPanel_SourceData {
            get {
                return ResourceManager.GetString("FullControlPanel_SourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входной файл.
        /// </summary>
        public static string FullControlPanel_SourceFile {
            get {
                return ResourceManager.GetString("FullControlPanel_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп.
        /// </summary>
        public static string FullControlPanel_StopButtonName {
            get {
                return ResourceManager.GetString("FullControlPanel_StopButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть входной файл.
        /// </summary>
        public static string MinControlPanel_OpenFileToolTip {
            get {
                return ResourceManager.GetString("MinControlPanel_OpenFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки моделирования.
        /// </summary>
        public static string MinControlPanel_OptionsToolTip {
            get {
                return ResourceManager.GetString("MinControlPanel_OptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать/скрыть консоль.
        /// </summary>
        public static string MinControlPanel_ShowOrHideLogWindow {
            get {
                return ResourceManager.GetString("MinControlPanel_ShowOrHideLogWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать информацию о программе.
        /// </summary>
        public static string MinControlPanel_ShowProgramInfo {
            get {
                return ResourceManager.GetString("MinControlPanel_ShowProgramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить моделирование.
        /// </summary>
        public static string MinControlPanel_StartModelingToolTip_Start {
            get {
                return ResourceManager.GetString("MinControlPanel_StartModelingToolTip_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать следующий шаг.
        /// </summary>
        public static string MinControlPanel_StartModelingToolTip_Step {
            get {
                return ResourceManager.GetString("MinControlPanel_StartModelingToolTip_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить моделирование.
        /// </summary>
        public static string MinControlPanel_StopModelingToolTip {
            get {
                return ResourceManager.GetString("MinControlPanel_StopModelingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свернуть панель управления.
        /// </summary>
        public static string MinimizeControlPanel {
            get {
                return ResourceManager.GetString("MinimizeControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка модулей программы прошла успешно.
        /// </summary>
        public static string ModulesLoadSuccessful {
            get {
                return ResourceManager.GetString("ModulesLoadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытие файла с входными данными.
        /// </summary>
        public static string OpenSourceFile_DialogTitle {
            get {
                return ResourceManager.GetString("OpenSourceFile_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входной файл не выбран!
        ///Откройте файл с данными и повторите попытку..
        /// </summary>
        public static string OpenSourceFile_FileNotOpened {
            get {
                return ResourceManager.GetString("OpenSourceFile_FileNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный файл не содержит данных для моделирования!
        ///Откройте файл с корректными данными и повторите попытку..
        /// </summary>
        public static string OpenSourceFile_IncorrectFile {
            get {
                return ResourceManager.GetString("OpenSourceFile_IncorrectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл данных (*.txt)|*.txt|Все файлы (*.*)|*.*.
        /// </summary>
        public static string OpenSourceFile_SupportedFormats {
            get {
                return ResourceManager.GetString("OpenSourceFile_SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Методы компановки не загружены!
        ///Чтобы выполнить компановку добавьте dll файл(ы) с методами компановки в папку plugins и перезапустите приложение..
        /// </summary>
        public static string PlaceMethodNotLoaded {
            get {
                return ResourceManager.GetString("PlaceMethodNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод компановки не выбран!
        ///Выберите метод и попробуйте снова..
        /// </summary>
        public static string PlaceMethodNotSelected {
            get {
                return ResourceManager.GetString("PlaceMethodNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компановка была прервана.
        /// </summary>
        public static string PlaceWereBreaked {
            get {
                return ResourceManager.GetString("PlaceWereBreaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компановка успешно завершена.
        /// </summary>
        public static string PlacingSuccessfulyEnded {
            get {
                return ResourceManager.GetString("PlacingSuccessfulyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание программы.
        /// </summary>
        public static string ProgramDescription {
            get {
                return ResourceManager.GetString("ProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название программы.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа выполняет действия.
        /// </summary>
        public static string ProgramStateDescription_Busy {
            get {
                return ResourceManager.GetString("ProgramStateDescription_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка в ходе работы программы.
        /// </summary>
        public static string ProgramStateDescription_Error {
            get {
                return ResourceManager.GetString("ProgramStateDescription_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всё в порядке, программа готова к работе.
        /// </summary>
        public static string ProgramStateDescription_Good {
            get {
                return ResourceManager.GetString("ProgramStateDescription_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с исходными данными был успешно загружен.
        /// </summary>
        public static string SourceFileLoaded_Successful {
            get {
                return ResourceManager.GetString("SourceFileLoaded_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить файл с исходными данными.
        /// </summary>
        public static string SourceFileLoaded_Unsuccessful {
            get {
                return ResourceManager.GetString("SourceFileLoaded_Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить.
        /// </summary>
        public static string StartButtonName_Start {
            get {
                return ResourceManager.GetString("StartButtonName_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаг.
        /// </summary>
        public static string StartButtonName_Step {
            get {
                return ResourceManager.GetString("StartButtonName_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется компановка печатной платы.
        /// </summary>
        public static string StartedPlacing {
            get {
                return ResourceManager.GetString("StartedPlacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется трасировка печатной платы.
        /// </summary>
        public static string StartedTracing {
            get {
                return ResourceManager.GetString("StartedTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масштаб.
        /// </summary>
        public static string StatusBar_ZoomToolTipName {
            get {
                return ResourceManager.GetString("StatusBar_ZoomToolTipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Методы трассировки не загружены!
        ///Чтобы выполнить трассировку добавьте dll файл(ы) с методами трассировки в папку plugins и перезапустите приложение..
        /// </summary>
        public static string TraceMethodIsNotLoaded {
            get {
                return ResourceManager.GetString("TraceMethodIsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод трассировки не выбран!
        ///Выберите метод и попробуйте снова..
        /// </summary>
        public static string TraceMethodIsNotSelected {
            get {
                return ResourceManager.GetString("TraceMethodIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трасировка была прервана.
        /// </summary>
        public static string TraceWereBreaked {
            get {
                return ResourceManager.GetString("TraceWereBreaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трассировка успешно завершена.
        /// </summary>
        public static string TracingSuccessfulyEnded {
            get {
                return ResourceManager.GetString("TracingSuccessfulyEnded", resourceCulture);
            }
        }
    }
}
